version: 2
jobs:
  build:
    docker:
    - image: hawkeye116477/pft:latest
    steps:
    - checkout
    - run: ./scripts/VICHS_auto.sh
    - add_ssh_keys
workflows:
  version: 2
  workflow:
    jobs:
      - build:
          context: org-global
