version: 2
jobs:
  CERT:
    docker:
    - image: polishfiltersteam/kad_image:2.26.9-2
    working_directory: ~/git/KAD
    steps:
    - checkout
    - run: ./scripts/addNoveltiesFromCert.py
    - persist_to_workspace:
        root: ./
        paths:
          - sections/CERT_novelties.txt
  LWS:
    docker:
    - image: polishfiltersteam/kad_image:2.26.9-2
    working_directory: ~/git/KAD
    steps:
    - checkout
    - run: ./scripts/ADD_NOVELTIES_FROM_LWS.sh
    - persist_to_workspace:
        root: ./
        paths:
          - sections/podejrzane_inne_oszustwa.txt
  Aktualizacja:
    docker:
    - image: polishfiltersteam/kad_image:2.26.9-2
    working_directory: ~/git/KAD
    steps:
    - checkout
    - attach_workspace:
        at: ./
    - run: ./scripts/build.sh
workflows:
  version: 2
  workflow:
    triggers:
    - schedule:
        cron: 15 0 * * 0
        filters:
          branches:
            only:
            - master
    jobs:
      - CERT
      - LWS
      - Aktualizacja:
          context: org-global
          requires:
            - CERT
            - LWS
