version: 2
jobs:
  CERT:
    docker:
    - image: polishfiltersteam/kad_image:2.26.9
    working_directory: ~/git/KAD
    steps:
    - checkout
    - run: ./scripts/ADD_NOVELTIES_FROM_CERT.sh
    - persist_to_workspace:
        root: ./
        paths:
          - sections/przekrety.txt
          - scripts/CERT_offline.txt
    - store_artifacts:
        path: sections/przekrety.txt
    - store_artifacts:
        path: scripts/CERT_offline.txt
  LWS:
    docker:
    - image: polishfiltersteam/kad_image:2.26.9
    working_directory: ~/git/KAD
    steps:
    - checkout
    - run: ./scripts/ADD_NOVELTIES_FROM_LWS.sh
    - persist_to_workspace:
        root: ./
        paths:
          - sections/podejrzane_inne_oszustwa.txt
  Aktualizacja:
    docker:
    - image: polishfiltersteam/kad_image:2.26.9
    working_directory: ~/git/KAD
    steps:
    - checkout
    - attach_workspace:
        at: ./
    - run: ./scripts/build.sh
workflows:
  version: 2
  workflow:
    triggers:
    - schedule:
        cron: 0 11,15,19,22 * * *
        filters:
          branches:
            only:
            - master
    jobs:
      - CERT
      - LWS
      - Aktualizacja:
          context: org-global
          requires:
            - CERT
            - LWS
