version: 2
jobs:
  build:
    docker:
    - image: polishfiltersteam/kad_image:latest
    steps:
    - checkout
    - run: ./scripts/VICHS_auto.sh
workflows:
  version: 2
  workflow:
    triggers:
    - schedule:
        cron: 0 11,15,19 * * *
        filters:
          branches:
            only:
            - master
    jobs:
      - build:
          context: org-global
