blank_issues_enabled: false
contact_links:
  - name: Off-topic
    url: https://github.com/PolishFiltersTeam/KAD/discussions/new
    about: Życzenia, powitania i inne sprawy nie pasujące do sekcji zgłoszeń, czyli plotkujemy o wszystkim i o niczym 🙂
