name: Aktualizacja listy

on:
  workflow_dispatch: null
  schedule:
      - cron: "0 8,12,16,20 * * *"

jobs:
  CERT:
    runs-on: ubuntu-latest
    container: ghcr.io/filtersheroes/kad_image:2.26.9
    steps:
      - uses: actions/checkout@v2
      - name: Dodawanie nowości z CERT
        env:
          SKIP_OFFLINE: true
        run: |
          ./scripts/ADD_NOVELTIES_FROM_CERT.sh
      - uses: actions/upload-artifact@v2
        with:
          name: CERT
          path: |
            sections/przekrety.txt
            scripts/CERT_offline.txt
  LWS:
    runs-on: ubuntu-latest
    container: ghcr.io/filtersheroes/kad_image:2.26.9
    steps:
      - uses: actions/checkout@v2
      - name: Dodawanie nowości z LWS
        run: |
          ./scripts/ADD_NOVELTIES_FROM_LWS.sh
      - uses: actions/upload-artifact@v2
        with:
          name: LWS
          path: sections/podejrzane_inne_oszustwa.txt
  Aktualizacja:
    needs: [CERT, LWS]
    runs-on: ubuntu-latest
    container: ghcr.io/filtersheroes/kad_image:2.26.9
    steps:
      - uses: actions/checkout@v2
      - uses: actions/download-artifact@v2
        with:
          path: sections
      - uses: actions/download-artifact@v2
        with:
          path: scripts
      - name: Aktualizacja całej listy
        env:
          GIT_TOKEN: ${{ secrets.GIT_TOKEN }}
        run: |
          ./scripts/build.sh
